// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2974.Walton2013.subsystems;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2974.Walton2013.RobotMap;
import org.usfirst.frc2974.Walton2013.commands.AimAndShoot;

/**
 *
 */
public class ShooterSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    CANJaguar shooterJag = RobotMap.shootershooterJag;
    Talon loader = RobotMap.loadTalon;
    Talon elevate = RobotMap.elevateTalon;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        setDefaultCommand(new AimAndShoot()); //driver cont, 0 angle, half wheel, don't shoot
    }

    public void spinUpWheel(double speed) { //turn on wheel
    }

    public boolean isWheelToSpeed() { //check if the shooter wheel is up to full speed
        return false;
    }

    public void SHOOT() { //shoot a frisbee
    }

    public void putAngleUp() { //put shooter angle up
    }

    public void putAngleDown() { //put shooter angle down
    }

    public void stopChangingAngle() { //stop changing angle of shooter
    }

    public void setAngle(double angle) { //set the shooter angle to "angle"; change to work
    }
}
