// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2974.Walton2013.subsystems;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2974.Walton2013.OI;
import org.usfirst.frc2974.Walton2013.RobotMap;
import org.usfirst.frc2974.Walton2013.commands.UseDrive;

/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    static CANJaguar rearRightTalon = RobotMap.driveTrainrearRightJag;
    static CANJaguar frontRightTalon = RobotMap.driveTrainfrontRightJag;
    static CANJaguar frontLeftTalon = RobotMap.driveTrainfrontLeftJag;
    static CANJaguar rearLeftTalon = RobotMap.driveTrainrearLeftJag;
    public static int TOUGHBOX_CODES_PER_REV = 360;

    public DriveTrain() {
        System.out.println("drive train constructor");
        try {
            frontRightTalon.setSpeedReference(CANJaguar.SpeedReference.kEncoder);
            frontLeftTalon.setSpeedReference(CANJaguar.SpeedReference.kEncoder);
            rearRightTalon.setSpeedReference(CANJaguar.SpeedReference.kEncoder);
            rearLeftTalon.setSpeedReference(CANJaguar.SpeedReference.kEncoder);

            frontRightTalon.configEncoderCodesPerRev(TOUGHBOX_CODES_PER_REV);
            frontLeftTalon.configEncoderCodesPerRev(TOUGHBOX_CODES_PER_REV);
            rearRightTalon.configEncoderCodesPerRev(TOUGHBOX_CODES_PER_REV);
            rearLeftTalon.configEncoderCodesPerRev(TOUGHBOX_CODES_PER_REV);

            frontRightTalon.setVoltageRampRate(35);
            frontLeftTalon.setVoltageRampRate(35);
            rearRightTalon.setVoltageRampRate(35);
            rearLeftTalon.setVoltageRampRate(35);

            frontRightTalon.enableControl();
            frontLeftTalon.enableControl();
            rearRightTalon.enableControl();
            rearLeftTalon.enableControl();
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void setDefault(Command c) {
        // System.out.println("Setting Default");
        setDefaultCommand(c);
    }

    public void initDefaultCommand() {
//        setDefaultCommand(new UseDrive(false, 0, false));
//        System.out.println("init default command drive");
    }

    public static void setSpeeds(double forward, double turn, double sideways) {
        forward = -forward;
        sideways = -sideways;
        double frontL = forward + turn + sideways;
        double frontR = forward - turn - sideways;
        double backL = forward + turn - sideways;
        double backR = forward - turn + sideways;
//        System.out.println("drive set speeds");
//        System.out.println("F: " + forward + "T: " + turn + "S: " + sideways);
        try {
            rearRightTalon.setX(backR);
            rearLeftTalon.setX(-backL);
            frontLeftTalon.setX(-frontL);
            frontRightTalon.setX(frontR);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }

    public static void STOP_DRIVE() {
        //System.out.println("STOPDRIVE STUFF");
        try {
            rearRightTalon.setX(0);
            rearLeftTalon.setX(0);
            frontLeftTalon.setX(0);
            frontRightTalon.setX(0);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }
    //PUT OTHER FUNCTIONS HERE!!!!!
}
