// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2974.Walton2013;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CANJaguar.*;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
        

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar driveTrainrearRightJag;
    public static CANJaguar driveTrainfrontRightJag;
    public static CANJaguar driveTrainfrontLeftJag;
    public static CANJaguar driveTrainrearLeftJag;
    public static CANJaguar shooterJaguar;
    public static CANJaguar conveyorJaguar;
    public static AnalogChannel potentiometer = new AnalogChannel(6);
    public static Talon fireTalon;
    public static Talon elevate;
    public static Talon frisbeeRollerFrisbeeRoller;
    public static Talon spatulaMotor;
    //public static
    
    public static final int REAR_RIGHT_JAG_CHANNEL = 11;
    public static final int FRONT_RIGHT_JAG_CHANNEL = 12;
    public static final int FRONT_LEFT_JAG_CHANNEL = 13;
    public static final int REAR_LEFT_JAG_CHANNEL = 14;
    public static final int SHOOTER_JAGUAR_CHANNEL = 15;
    public static final int CONVEYOR_JAG_CHANNEL = 16;
    
    public static final int SENS_A = 4;
    public static final int SENS_B = 3;
    public static final int SENS_C = 2;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        try { 
            driveTrainrearRightJag = new CANJaguar(2);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            driveTrainfrontRightJag = new CANJaguar(3);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            driveTrainfrontLeftJag = new CANJaguar(4);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            driveTrainrearLeftJag = new CANJaguar(5);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            shooterJaguar = new CANJaguar(6);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            conveyorJaguar = new CANJaguar(7);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
